# SETTINGS VALUES:
#  (MX Platforms will be checked for network-services mode Enhanced-IP automatically)
#  (Nonstop routing in PIM config will also be handled automatically)

# LOCAL DIRECTORY ON THE SERVER FOR IMAGES
CODE_FOLDER: '/opt/code/Juniper/Approved/MX/MX960/'

# DIRECTORY AND IMAGE NAMES ON THE DEVICE TO BE UPGRADED
CODE_DEST: '/var/tmp/'
CODE_NAME: '16.1R6-S1.1'
CODE_IMAGE64: 'junos-install-mx-x86-64-16.1R6-S1.1.tgz'
CODE_IMAGE32: 'junos-install-mx-x86-32-16.1R6-S1.1.tgz'

# DIRECTORY AND IMAGE NAMES IF A 2-STAGE UPGRADE IS NEEDED
CODE_PRESERVE: '/var/preserve/'
CODE_2STAGE_NAME: '13.3R6-S1.6'
CODE_2STAGE64: 'jinstall64-13.3R6-S1.6-domestic-signed.tgz'
CODE_2STAGE32: 'jinstall-13.3R6-S1.6-domestic-signed.tgz'

# JSU NAMES IF REQUIRED
CODE_JSU_NAME: '16.1R6-S1-J2'
CODE_JSU32: 'jselective-update-J2-x86-32-16.1R6-S1-J2.tgz'
CODE_JSU64: 'jselective-update-amd64-J2-x86-64-16.1R6-S1-J2.tgz'

# CONFIG COMANDS TO BE RUN BEFORE STARTING THE UPGRADE
PRE_UPGRADE_CMDS:
  - 'delete chassis redundancy failover'
  - 'delete chassis redundancy graceful-switchover'
  - 'delete routing-options nonstop-routing'
  - 'delete protocols isis overload'
  - 'set protocols isis overload advertise-high-metrics'

# CONFIG COMANDS TO BE RUN AFTER THE UPGRADE IS COMPLETE
POST_UPGRADE_CMDS:
  - 'set routing-options nonstop-routing'
  - 'set chassis redundancy failover on-loss-of-keepalives'
  - 'set chassis redundancy graceful-switchover'
  - 'delete protocols isis overload'
  - 'set protocols isis overload timeout 600'
  - 'set protocols isis overload advertise-high-metrics'
